### ISSUE TITLE
Prise en charge des Pixoo Max (32x32)

### ISSUE THREAD

**Issue by Arubinu** [virtualabs/pixoo-client#1]
Bonjour,

J'ai reçu mes Pixoo Max et ton code fonctionne autant que bien mais uniquement comme un 16x16.
En regardant le code j'ai vu le tableau de 16x16 pixels et ai donc essayé de mettre une variable, sauf que lorsque je le met en 32 tout part en live.

Pourrais-tu adapter le code pour cet usage, parce que je ne suis pas suffisamment calé pour faire cette modification ^^

**Comment by virtualabs** [comment]
C'est désormais pris en charge, et le merge de la PR #4 a réglé les derniers soucis avec les images.
